// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mazsTSCdeXMvNewzsED8CP
// Component: j0txJ-a09lq

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { PlasmicHead } from "@plasmicapp/react-web"; // plasmic-import: 7EBFWZs-Lh/codeComponent
import { NavigationBar } from "@plasmicpkgs/plasmic-nav"; // plasmic-import: jGx9tiKJoex/codeComponent
import Collapsible from "../../Collapsible"; // plasmic-import: Z0pRxdl5sa/component

import { useScreenVariants as useScreenVariantsqbGzfD819Z3T3 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: QBGzfD819Z3t3/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic_sandbox_satuhsehat.module.css"; // plasmic-import: mazsTSCdeXMvNewzsED8CP/projectcss
import sty from "./PlasmicOldHomepage.module.css"; // plasmic-import: j0txJ-a09lq/css

import LawSvgrepoCom1SvgIcon from "./icons/PlasmicIcon__LawSvgrepoCom1Svg"; // plasmic-import: jj3V4MmrRO/icon
import JusticeSvgrepoCom1SvgIcon from "./icons/PlasmicIcon__JusticeSvgrepoCom1Svg"; // plasmic-import: d11xSBFAIc/icon
import Frame1000001301SvgIcon from "./icons/PlasmicIcon__Frame1000001301Svg"; // plasmic-import: HdY_vWMIj2/icon
import MedicineDrugHealthMedicalSmartphonePharmacyTabletSvgrepoCom1SvgIcon from "./icons/PlasmicIcon__MedicineDrugHealthMedicalSmartphonePharmacyTabletSvgrepoCom1Svg"; // plasmic-import: a7fWEtdh_m/icon
import HeartbeatHeartHealthPulseSmartphoneMedicalRateSvgrepoCom1SvgIcon from "./icons/PlasmicIcon__HeartbeatHeartHealthPulseSmartphoneMedicalRateSvgrepoCom1Svg"; // plasmic-import: KmthYfnQUS/icon
import MedicineDrugHealthMedicalSmartphonePharmacyTablet2SvgrepoComsvgIcon from "./icons/PlasmicIcon__MedicineDrugHealthMedicalSmartphonePharmacyTablet2SvgrepoComsvg"; // plasmic-import: VzvMwKKQ1a/icon
import MobilePhoneChatHealthDeviceTelephoneSmartphoneSvgrepoComsvgIcon from "./icons/PlasmicIcon__MobilePhoneChatHealthDeviceTelephoneSmartphoneSvgrepoComsvg"; // plasmic-import: KLL8rlOJRh/icon

export type PlasmicOldHomepage__VariantMembers = {};
export type PlasmicOldHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicOldHomepage__VariantsArgs;
export const PlasmicOldHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicOldHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicOldHomepage__ArgsType;
export const PlasmicOldHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicOldHomepage__OverridesType = {
  root?: p.Flex<"div">;
  pageMetadataOverride?: p.Flex<typeof PlasmicHead>;
  header?: p.Flex<"div">;
  navigationBar?: p.Flex<typeof NavigationBar>;
  hero?: p.Flex<"section">;
  about?: p.Flex<"div">;
  why?: p.Flex<"div">;
  who?: p.Flex<"div">;
  card5?: p.Flex<"div">;
  card6?: p.Flex<"div">;
  card7?: p.Flex<"div">;
  card8?: p.Flex<"div">;
  faq?: p.Flex<"div">;
  who2?: p.Flex<"div">;
  footer?: p.Flex<"div">;
};

export interface DefaultOldHomepageProps {}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicOldHomepage__RenderFunc(props: {
  variants: PlasmicOldHomepage__VariantsArgs;
  args: PlasmicOldHomepage__ArgsType;
  overrides: PlasmicOldHomepage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsqbGzfD819Z3T3()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicOldHomepage.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicOldHomepage.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicOldHomepage.pageMetadata.title}
        />
        <meta
          key="description"
          name="description"
          content={PlasmicOldHomepage.pageMetadata.description}
        />
        <meta
          key="og:description"
          property="og:description"
          content={PlasmicOldHomepage.pageMetadata.description}
        />
        <meta
          key="twitter:description"
          name="twitter:description"
          content={PlasmicOldHomepage.pageMetadata.description}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.root
          )}
        >
          <PlasmicHead
            data-plasmic-name={"pageMetadataOverride"}
            data-plasmic-override={overrides.pageMetadataOverride}
            className={classNames("__wab_instance", sty.pageMetadataOverride)}
          />

          <div
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames(projectcss.all, sty.header)}
          >
            <NavigationBar
              data-plasmic-name={"navigationBar"}
              data-plasmic-override={overrides.navigationBar}
              brand={
                <p.PlasmicLink
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.link__b3Om1
                  )}
                  component={Link}
                  href={"#" as const}
                  platform={"nextjs"}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__slE)}
                    displayHeight={"40px" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"none" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    src={{
                      src: "/plasmic/sandbox_satuhsehat/images/logokemkespng.png",
                      fullWidth: 133,
                      fullHeight: 60,
                      aspectRatio: undefined
                    }}
                  />
                </p.PlasmicLink>
              }
              className={classNames("__wab_instance", sty.navigationBar)}
              closeButton={
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__ygjon)}
                  displayHeight={"auto" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"none" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"auto" as const}
                  src={"https://static1.plasmic.app/close.svg" as const}
                />
              }
              itemsGap={24 as const}
              menuItems={
                <React.Fragment>
                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link___5X7Sn
                    )}
                    component={Link}
                    href={"/" as const}
                    platform={"nextjs"}
                  >
                    {"Beranda"}
                  </p.PlasmicLink>
                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__b33S
                    )}
                    component={Link}
                    href={"#about" as const}
                    platform={"nextjs"}
                  >
                    {"Tentang"}
                  </p.PlasmicLink>
                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__u8Mze
                    )}
                    component={Link}
                    href={"#faq" as const}
                    platform={"nextjs"}
                  >
                    {"FAQ"}
                  </p.PlasmicLink>
                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__aKdhY
                    )}
                    component={Link}
                    href={`/dokumen`}
                    platform={"nextjs"}
                  >
                    {"Dokumen"}
                  </p.PlasmicLink>
                </React.Fragment>
              }
              openButton={
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___29Yui)}
                  displayHeight={"auto" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"none" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"auto" as const}
                  src={"https://static1.plasmic.app/menu.svg" as const}
                />
              }
              responsiveBreakpoint={768 as const}
            />
          </div>
          <p.Stack
            as={"section"}
            data-plasmic-name={"hero"}
            data-plasmic-override={overrides.hero}
            hasGap={true}
            className={classNames(projectcss.all, sty.hero)}
          >
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__r0GEt)}
              displayHeight={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? ("500px" as const)
                  : ("auto" as const)
              }
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"auto" as const}
              loading={"lazy" as const}
              src={{
                src: "/plasmic/sandbox_satuhsehat/images/_22022023BannerRegsan5760X2252Px3Fa2Minjpg.jpeg",
                fullWidth: 5760,
                fullHeight: 2252,
                aspectRatio: undefined
              }}
            />

            <div className={classNames(projectcss.all, sty.columns__lvfh)}>
              {(
                hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
              ) ? (
                <div
                  className={classNames(projectcss.all, sty.column___6EhrH)}
                />
              ) : null}
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__yVvgd)}
              >
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__pViEy
                  )}
                >
                  {"Regulatory Sandbox Kemenkes RI"}
                </h2>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__dxAUm
                  )}
                >
                  {
                    "Ruang Uji Bagi Penyelenggara Inovasi Digital Kesehatan di Indonesia"
                  }
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__lshAl
                  )}
                >
                  {"Pendaftaran dibuka tanggal 3 April  - 12 Mei 2023"}
                </div>
                {true ? (
                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__olBtp
                    )}
                    component={Link}
                    href={"https://ee-kobo.kemkes.go.id/x/9DmKdgeZ" as const}
                    platform={"nextjs"}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__gbpy5
                      )}
                    >
                      {"Daftar Sekarang"}
                    </div>
                  </p.PlasmicLink>
                ) : null}
              </p.Stack>
            </div>
          </p.Stack>
          <div
            data-plasmic-name={"about"}
            data-plasmic-override={overrides.about}
            className={classNames(projectcss.all, sty.about)}
            id={"about" as const}
          >
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__pLy32)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__yY8BF)}
              >
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__gvvs9
                  )}
                >
                  {"Apa itu Regulatory Sandbox ?"}
                </h2>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___5UlIx
                  )}
                >
                  {
                    "Regulatory sandbox adalah mekanisme pengujian bagi penyelenggara inovasi digital kesehatan (IDK) yang dilakukan oleh Kementerian Kesehatan RI (Kemenkes) untuk menilai keandalan proses bisnis, model bisnis, teknologi, dan tata kelola. Pembelajaran selama proses uji dapat menjadi rekomendasi pengembangan kebijakan berbasis bukti oleh Kemenkes.\n\nIDK akan dikelompokkan ke dalam klaster prioritas, seperti telekesehatan, telefarmasi, on-demand healthcare (lokapasar kesehatan), artificial intelligence dan klaster lainnya sesuai dengan perkembangan teknologi.\n\nSkema uji coba inovasi digital kesehatan melalui regulatory sandbox telah dilakukan pertama kali di Indonesia pada penyakit malaria melalui Keputusan Direktorat Jenderal Pencegahan dan Pengendalian Penyakit No. HK.02.02/1/3090/2021 pada 2021-2023. Dari pengalaman tersebut, Kemenkes RI kini memperluas penerapan regulatory sandbox pada model bisnis IDK yang lebih beragam."
                  }
                </div>
              </p.Stack>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__djmhs)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___2RLg2)}
                  displayHeight={"auto" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"auto" as const}
                  loading={"lazy" as const}
                  src={{
                    src: "/plasmic/sandbox_satuhsehat/images/sandboxpng.png",
                    fullWidth: 899,
                    fullHeight: 899,
                    aspectRatio: undefined
                  }}
                />
              </p.Stack>
            </p.Stack>
          </div>
          <div
            data-plasmic-name={"why"}
            data-plasmic-override={overrides.why}
            className={classNames(projectcss.all, sty.why)}
          >
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___94V9S)}
              >
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__hWnQw
                  )}
                >
                  {"Kenapa perlu mendaftar regulatory sandbox?"}
                </h2>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.columns__ln2Pj)}
                >
                  <div
                    className={classNames(projectcss.all, sty.column__jBvyo)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__bWyub)}
                    >
                      <LawSvgrepoCom1SvgIcon
                        className={classNames(projectcss.all, sty.svg__c208S)}
                        role={"img"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__v6WP
                        )}
                      >
                        {
                          "Mendapatkan asesmen kesesuaian dengan regulasi dan praktik baik inovasi"
                        }
                      </div>
                    </p.Stack>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__zJjD9)}
                  >
                    {true ? (
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__lQwYn
                        )}
                      >
                        <JusticeSvgrepoCom1SvgIcon
                          className={classNames(projectcss.all, sty.svg__nYzMf)}
                          role={"img"}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__sduD
                          )}
                        >
                          {
                            "Berpartisipasi dalam pemberian rekomendasi kebijakan terkait teknologi kesehatan"
                          }
                        </div>
                      </p.Stack>
                    ) : null}
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column___25GLc)}
                  >
                    {true ? (
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__cUwDg
                        )}
                      >
                        <Frame1000001301SvgIcon
                          className={classNames(projectcss.all, sty.svg__kP2O8)}
                          role={"img"}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___7BkFd
                          )}
                        >
                          {
                            "Terdaftar sebagai mitra resmi Kemenkes untuk pengembangan regulasi dan ekosistem kesehatan di Indonesia"
                          }
                        </div>
                      </p.Stack>
                    ) : null}
                  </div>
                </p.Stack>
              </p.Stack>
            ) : null}
          </div>
          <div
            data-plasmic-name={"who"}
            data-plasmic-override={overrides.who}
            className={classNames(projectcss.all, sty.who)}
          >
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__sPaZc)}
              >
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__r3R0E
                  )}
                >
                  {"Untuk Siapa ?"}
                </h2>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__b46NS
                  )}
                >
                  {
                    "Regulatory Sandbox akan dimulai bagi pelaku usaha non perseorangan Inovasi Digital Kesehatan (IDK) yang telah terdaftar sebagai Penyelenggara Sistem Elektronik (PSE) dan memiliki bisnis pada klaster Telekesehatan berikut"
                  }
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__hJe3X)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__taPh)}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"card5"}
                      data-plasmic-override={overrides.card5}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.card5)}
                    >
                      {true ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__bBaaM
                          )}
                        >
                          <MedicineDrugHealthMedicalSmartphonePharmacyTabletSvgrepoCom1SvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__btN1B
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}
                      <h5
                        className={classNames(
                          projectcss.all,
                          projectcss.h5,
                          projectcss.__wab_text,
                          sty.h5__ssV9L
                        )}
                      >
                        {"Telekonsultasi"}
                      </h5>
                    </p.Stack>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__u9QQq)}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"card6"}
                      data-plasmic-override={overrides.card6}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.card6)}
                    >
                      {true ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__oem2R
                          )}
                        >
                          <HeartbeatHeartHealthPulseSmartphoneMedicalRateSvgrepoCom1SvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__iqJdj
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}
                      <h5
                        className={classNames(
                          projectcss.all,
                          projectcss.h5,
                          projectcss.__wab_text,
                          sty.h5__vm4Sj
                        )}
                      >
                        {"Telemonitoring"}
                      </h5>
                    </p.Stack>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__r3IhC)}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"card7"}
                      data-plasmic-override={overrides.card7}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.card7)}
                    >
                      {true ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__sqrkO
                          )}
                        >
                          <MedicineDrugHealthMedicalSmartphonePharmacyTablet2SvgrepoComsvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg___3951A
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}
                      <h5
                        className={classNames(
                          projectcss.all,
                          projectcss.h5,
                          projectcss.__wab_text,
                          sty.h5__yneQm
                        )}
                      >
                        {"Telemedicine"}
                      </h5>
                    </p.Stack>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__mny3)}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"card8"}
                      data-plasmic-override={overrides.card8}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.card8)}
                    >
                      {true ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__xJkT3
                          )}
                        >
                          <MobilePhoneChatHealthDeviceTelephoneSmartphoneSvgrepoComsvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__qjLw3
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}
                      <h5
                        className={classNames(
                          projectcss.all,
                          projectcss.h5,
                          projectcss.__wab_text,
                          sty.h5__kuLjR
                        )}
                      >
                        {"Komunikasi, Informasi, Edukasi Kesehatan"}
                      </h5>
                    </p.Stack>
                  </div>
                </div>
                <h5
                  className={classNames(
                    projectcss.all,
                    projectcss.h5,
                    projectcss.__wab_text,
                    sty.h5__snWe3
                  )}
                >
                  {"dan praktik telekesehatan lainnya"}
                </h5>
              </p.Stack>
            ) : null}
          </div>
          <div
            data-plasmic-name={"faq"}
            data-plasmic-override={overrides.faq}
            className={classNames(projectcss.all, sty.faq)}
            id={"faq" as const}
          >
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__myxic)}
              >
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__jsOba
                  )}
                >
                  {"FAQ"}
                </h2>
                <div className={classNames(projectcss.all, sty.columns__rS7T3)}>
                  <div className={classNames(projectcss.all, sty.column__peiU)}>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__jvA7R)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__tiZAz
                        )}
                      >
                        <Collapsible
                          className={classNames(
                            "__wab_instance",
                            sty.collapsible__zv8J8
                          )}
                          slot={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__aoGGq
                              )}
                            >
                              {"Apa itu regulatory sandbox?"}
                            </div>
                          }
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__uOQnh
                            )}
                          >
                            <React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ fontStyle: "italic" }}
                              >
                                {"Regulatory sandbox"}
                              </span>
                              <React.Fragment>
                                {
                                  " adalah mekanisme pengujian untuk penyelenggara inovasi digital kesehatan (IDK) yang dilakukan oleh Kementerian Kesehatan RI  untuk menilai keandalan proses bisnis, model bisnis, teknologi, serta tata kelola sebagai pembelajaran selama proses uji yang dapat menjadi rekomendasi pengembangan regulasi berbasis bukti."
                                }
                              </React.Fragment>
                            </React.Fragment>
                          </div>
                        </Collapsible>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__zCyWv
                        )}
                      >
                        <Collapsible
                          className={classNames(
                            "__wab_instance",
                            sty.collapsible__zyamN
                          )}
                          slot={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__vwyZs
                              )}
                            >
                              {
                                "Siapa yang dapat mendaftar regulatory sandbox? "
                              }
                            </div>
                          }
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__zhaGb
                            )}
                          >
                            <React.Fragment>
                              <React.Fragment>{"Peserta "}</React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ fontStyle: "italic" }}
                              >
                                {"regulatory sandbox"}
                              </span>
                              <React.Fragment>
                                {
                                  " merupakan penyelenggara IDK yang memenuhi ketentuan sebagaimana dimaksud dalam panduan ini yaitu sebagai berikut:"
                                }
                              </React.Fragment>
                            </React.Fragment>
                          </div>
                          <ul
                            className={classNames(
                              projectcss.all,
                              projectcss.ul,
                              sty.ul__qZnuK
                            )}
                          >
                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.li__euwa
                              )}
                            >
                              {
                                "Pelaku usaha non perseorangan sebagaimana diatur dalam peraturan perundang-undangan terkait perizinan usaha terintegrasi;"
                              }
                            </li>
                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.li__kryv0
                              )}
                            >
                              {
                                "Melaksanakan kegiatan usaha secara luas atau sudah dilaksanakan (pengguna dan kegiatan usaha) pada minimal dua provinsi; dan"
                              }
                            </li>
                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.li__fFgU
                              )}
                            >
                              {
                                "Inovasi yang dapat menimbulkan kompleksitas dari sisi teknologi dan penggunaannya;"
                              }
                            </li>
                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.li__kdpzj
                              )}
                            >
                              <React.Fragment>
                                <React.Fragment>
                                  {
                                    "Merupakan bagian dari klaster yang tengah menjadi fokus "
                                  }
                                </React.Fragment>
                                <span
                                  className={
                                    "plasmic_default__all plasmic_default__span"
                                  }
                                  style={{ fontStyle: "italic" }}
                                >
                                  {"regulatory sandbox"}
                                </span>
                                <React.Fragment>
                                  {
                                    " (untuk tahap awal ini klaster telekesehatan yang terdiri dari Telekonsultasi, Telemonitoring, Telemedicine, Komunikasi, Edukasi, Informasi (KIE), dan teknologi telekesehatan lainnya."
                                  }
                                </React.Fragment>
                              </React.Fragment>
                            </li>
                          </ul>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__sRrdp
                            )}
                          >
                            {
                              "Pelaku usaha non perseorangan sebagaimana diatur dalam peraturan perundang-undangan terkait perizinan usaha terintegrasi, antara lain:"
                            }
                          </div>
                          <ul
                            className={classNames(
                              projectcss.all,
                              projectcss.ul,
                              sty.ul___7ToOv
                            )}
                          >
                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.li__ppOGz
                              )}
                            >
                              {"Perseroan terbatas;"}
                            </li>
                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.li__ukbz7
                              )}
                            >
                              {"Perusahaan umum;"}
                            </li>
                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.li___7Ks1V
                              )}
                            >
                              {"Perusahaan umum daerah;"}
                            </li>
                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.li__pPiVb
                              )}
                            >
                              {"Badan hukum lainnya yang dimiliki oleh negara;"}
                            </li>
                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.li__wMe5Y
                              )}
                            >
                              {"Badan layanan umum;"}
                            </li>
                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.li__jLDep
                              )}
                            >
                              {"Lembaga penyiaran;"}
                            </li>
                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.li__tTpd7
                              )}
                            >
                              {"Badan usaha yang didirikan oleh yayasan;"}
                            </li>
                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.li__rcoG6
                              )}
                            >
                              {"Koperasi;"}
                            </li>
                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.li__gZyo9
                              )}
                            >
                              {"Persekutuan komanditer;"}
                            </li>
                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.li__iJdxq
                              )}
                            >
                              {"Persekutuan firma; dan"}
                            </li>
                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.li__cOouL
                              )}
                            >
                              {"Persekutuan perdata."}
                            </li>
                          </ul>
                        </Collapsible>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__jqgRe
                        )}
                      >
                        <Collapsible
                          className={classNames(
                            "__wab_instance",
                            sty.collapsible__bPqgF
                          )}
                          slot={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__jKgOh
                              )}
                            >
                              {
                                "Apakah ada kewajiban setiap penyelenggara IDK mengikuti regulatory sandbox?"
                              }
                            </div>
                          }
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__ejtK0
                            )}
                          >
                            <React.Fragment>
                              <React.Fragment>
                                {"Penyelenggara IDK dihimbau untuk mendaftar "}
                              </React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ fontStyle: "italic" }}
                              >
                                {"regulatory sandbox"}
                              </span>
                              <React.Fragment>
                                {
                                  " dalam rangka turut serta dalam memberi masukan bagi pembuat kebijakan (regulator) serta dalam rangka melakukan perlindungan pengguna inovasi."
                                }
                              </React.Fragment>
                            </React.Fragment>
                          </div>
                        </Collapsible>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__ziGu5
                        )}
                      >
                        <Collapsible
                          className={classNames(
                            "__wab_instance",
                            sty.collapsible___5VQid
                          )}
                          slot={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__paksg
                              )}
                            >
                              {
                                "Apakah regulatory sandbox hanya untuk inovasi digital kesehatan dalam negeri?"
                              }
                            </div>
                          }
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__oLnFs
                            )}
                          >
                            <React.Fragment>
                              <React.Fragment>{"Ya. "}</React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ fontStyle: "italic" }}
                              >
                                {"Regulatory sandbox"}
                              </span>
                              <React.Fragment>
                                {
                                  " oleh Kementerian Kesehatan RI diperuntukkan bagi pelaku industri penyelenggara IDK dalam negeri yang memiliki inovasi kesehatan disruptif. Saat ini r"
                                }
                              </React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ fontStyle: "italic" }}
                              >
                                {"egulatory sandbox"}
                              </span>
                              <React.Fragment>
                                {
                                  " diberlakukan untuk klaster telekesehatan dan ke depannya akan diperluas ke klaster prioritas lainnya."
                                }
                              </React.Fragment>
                            </React.Fragment>
                          </div>
                        </Collapsible>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__v7XRp
                        )}
                      >
                        <Collapsible
                          className={classNames(
                            "__wab_instance",
                            sty.collapsible__muAAm
                          )}
                          slot={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__isvLc
                              )}
                            >
                              {"Kapan saya perlu mengikuti Regulatory Sandbox?"}
                            </div>
                          }
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__ozWKw
                            )}
                          >
                            {
                              "Setiap penyelenggara IDK pada klaster prioritas yang telah diumumkan oleh Kementerian Kesehatan RI, diberikan waktu satu bulan untuk melakukan pendaftaran dan mengikuti proses pendaftaran untuk mendapatkan rekomendasi."
                            }
                          </div>
                        </Collapsible>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__ioFf
                        )}
                      >
                        <Collapsible
                          className={classNames(
                            "__wab_instance",
                            sty.collapsible__n2Sp
                          )}
                          slot={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__gg48S
                              )}
                            >
                              {
                                "Ruang lingkup apa saja yang diuji dalam regulatory sandbox?"
                              }
                            </div>
                          }
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__gfFmr
                            )}
                          >
                            <React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ fontStyle: "italic" }}
                              >
                                {"Regulatory sandbox "}
                              </span>
                              <React.Fragment>
                                {
                                  "menguji penyelenggara IDK pada aspek berikut:\n- Penerimaan pengguna (user acceptance test)\n- Standar teknologi\n- Keamanan dan perlindungan data pengguna\n- Inklusivitas\n\nTerdapat juga aspek-aspek lain yang diuji pada masing-masing klaster yang akan ditentukan oleh Kementerian Kesehatan dan tim panel."
                                }
                              </React.Fragment>
                            </React.Fragment>
                          </div>
                        </Collapsible>
                      </div>
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column___8W4Pe)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__ibGuo)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__pWbwU
                        )}
                      >
                        <Collapsible
                          className={classNames(
                            "__wab_instance",
                            sty.collapsible__oH4Ol
                          )}
                          slot={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___9KzAc
                              )}
                            >
                              {
                                "Bagaimana proses pendaftaran regulatory sandbox"
                              }
                            </div>
                          }
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__wfOze
                            )}
                          >
                            <React.Fragment>
                              <React.Fragment>
                                {"Proses pendaftaran "}
                              </React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ fontStyle: "italic" }}
                              >
                                {"regulatory sandbox"}
                              </span>
                              <React.Fragment>
                                {
                                  " meliputi:\n\n1. Pengisian formulir pendaftaran\nTahap ini terdiri atas pengisian formulir pendaftaran secara "
                                }
                              </React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ fontStyle: "italic" }}
                              >
                                {"online"}
                              </span>
                              <React.Fragment>
                                {
                                  ". \n\n2. Verifikasi dan validasi pendaftaran\nPenyelenggara IDK yang lolos verifikasi dan validasi akan diberikan status tercatat. Selanjutnya peserta akan mendapatkan nomor registrasi atas status tercatat.\n\n3. Seleksi dan kategorisasi klaster inovasi\nPada tahap ini, penyelenggara IDK akan melanjutkan proses seleksi untuk dapat ikut serta dalam "
                                }
                              </React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ fontStyle: "italic" }}
                              >
                                {"regulatory sandbox"}
                              </span>
                              <React.Fragment>
                                {
                                  ". Pengumuman akan diinformasikan melalui kanal publikasi resmi Kementerian Kesehatan Republik Indonesia kepada penyelenggara IDK."
                                }
                              </React.Fragment>
                            </React.Fragment>
                          </div>
                        </Collapsible>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___4LB7C
                        )}
                      >
                        <Collapsible
                          className={classNames(
                            "__wab_instance",
                            sty.collapsible__hkpS
                          )}
                          slot={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__oVbjd
                              )}
                            >
                              {
                                "Berapa lama waktu yang diperlukan untuk mendaftar sampai mendapatkan rekomendasi regulatory sandbox?"
                              }
                            </div>
                          }
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___7F1KG
                            )}
                          >
                            <React.Fragment>
                              <React.Fragment>
                                {
                                  "Total estimasi waktu yang dibutuhkan untuk menyelesaikan proses pendaftaran hingga pemberian rekomendasi pada "
                                }
                              </React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ fontStyle: "italic" }}
                              >
                                {"regulatory sandbox"}
                              </span>
                              <React.Fragment>
                                {
                                  " adalah 8-14 bulan. Perbedaan waktu keluarnya rekomendasi tergantung dengan ada atau tidaknya perbaikan, berikut simulasi waktu perihal tahapan yang disebutkan:\n\n- Pendaftaran sampai Seleksi dan Kategorisasi Klaster : 2 Bulan\n- Pengujian sampai Rekomendasi (tanpa perbaikan) : 6 bulan\n- Pengujian sampai Rekomendasi (dengan waktu perbaikan maksimal) : 14 bulan"
                                }
                              </React.Fragment>
                            </React.Fragment>
                          </div>
                        </Collapsible>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__uyxfE
                        )}
                      >
                        <Collapsible
                          className={classNames(
                            "__wab_instance",
                            sty.collapsible__fKksy
                          )}
                          slot={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__dXk2V
                              )}
                            >
                              {
                                "Dokumen apa saja yang diperlukan untuk mendaftar regulatory sandbox?"
                              }
                            </div>
                          }
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__moUvo
                            )}
                          >
                            {
                              "Berikut ini beberapa dokumen yang perlu disiapkan untuk mendaftar regulatory sandbox, yaitu:"
                            }
                          </div>
                          <ul
                            className={classNames(
                              projectcss.all,
                              projectcss.ul,
                              sty.ul__fkAb
                            )}
                          >
                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.li__bd7Au
                              )}
                            >
                              {
                                "Persyaratan dasar (proses lintas kementerian/lembaga)\n"
                              }
                            </li>
                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                sty.li__y02Ca
                              )}
                            >
                              <ul
                                className={classNames(
                                  projectcss.all,
                                  projectcss.ul,
                                  sty.ul___8Wgh0
                                )}
                              >
                                <li
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.li,
                                    projectcss.__wab_text,
                                    sty.li__qASzS
                                  )}
                                >
                                  <React.Fragment>
                                    {(() => {
                                      try {
                                        return "Memiliki Akta Pendirian Perusahaan dari Kementerian Hukum dan Hak Asasi Manusia (Kementerian Hukum dan Hak Asasi Manusia RI);";
                                      } catch (e) {
                                        if (
                                          e instanceof TypeError ||
                                          e?.plasmicType ===
                                            "PlasmicUndefinedDataError"
                                        ) {
                                          return "Enter some text";
                                        }
                                        throw e;
                                      }
                                    })()}
                                  </React.Fragment>
                                </li>
                                <li
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.li,
                                    projectcss.__wab_text,
                                    sty.li__biyt5
                                  )}
                                >
                                  <React.Fragment>
                                    {(() => {
                                      try {
                                        return "Memiliki Nomor Induk Berusaha (NIB) dari Sistem Online Single Submission (OSS) dan Klasifikasi Baku Lapangan Usaha Indonesia (KBLI);";
                                      } catch (e) {
                                        if (
                                          e instanceof TypeError ||
                                          e?.plasmicType ===
                                            "PlasmicUndefinedDataError"
                                        ) {
                                          return "Enter some text";
                                        }
                                        throw e;
                                      }
                                    })()}
                                  </React.Fragment>
                                </li>
                                <li
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.li,
                                    projectcss.__wab_text,
                                    sty.li__kBAs
                                  )}
                                >
                                  <React.Fragment>
                                    {(() => {
                                      try {
                                        return "Memiliki bukti registrasi dari Kominfo sebagai Penyelenggara Sistem Elektronik (PSE); dan";
                                      } catch (e) {
                                        if (
                                          e instanceof TypeError ||
                                          e?.plasmicType ===
                                            "PlasmicUndefinedDataError"
                                        ) {
                                          return "Enter some text";
                                        }
                                        throw e;
                                      }
                                    })()}
                                  </React.Fragment>
                                </li>
                                <li
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.li,
                                    projectcss.__wab_text,
                                    sty.li__hYyr2
                                  )}
                                >
                                  <React.Fragment>
                                    {(() => {
                                      try {
                                        return "Mencantumkan bukti telah melakukan penetration testing (pentest) atau mencantumkan sertifikasi keamanan yang dimiliki.";
                                      } catch (e) {
                                        if (
                                          e instanceof TypeError ||
                                          e?.plasmicType ===
                                            "PlasmicUndefinedDataError"
                                        ) {
                                          return "Enter some text";
                                        }
                                        throw e;
                                      }
                                    })()}
                                  </React.Fragment>
                                </li>
                              </ul>
                            </li>
                          </ul>
                          <ul
                            className={classNames(
                              projectcss.all,
                              projectcss.ul,
                              sty.ul__et50G
                            )}
                          >
                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.li__bbEjf
                              )}
                            >
                              {"Informasi Perusahaan"}
                            </li>
                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                sty.li__aYgcj
                              )}
                            >
                              <ul
                                className={classNames(
                                  projectcss.all,
                                  projectcss.ul,
                                  sty.ul__boKsv
                                )}
                              >
                                <li
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.li,
                                    projectcss.__wab_text,
                                    sty.li__q0UI
                                  )}
                                >
                                  {"Profil perusahaan"}
                                </li>
                                <li
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.li,
                                    projectcss.__wab_text,
                                    sty.li__uLW
                                  )}
                                >
                                  {
                                    "Model bisnis yang dijalankan dan yang akan dikembangkan\n"
                                  }
                                </li>
                                <li
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.li,
                                    projectcss.__wab_text,
                                    sty.li__seX1N
                                  )}
                                >
                                  {"Penjelasan mengenai produk "}
                                </li>
                                <li
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.li,
                                    projectcss.__wab_text,
                                    sty.li__w3P3H
                                  )}
                                >
                                  {
                                    "Kebijakan penyimpanan data dan privasi produk (syarat dan ketentuan)"
                                  }
                                </li>
                                <li
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.li,
                                    projectcss.__wab_text,
                                    sty.li__eaKcx
                                  )}
                                >
                                  {"Rencana bisnis 5-10 tahun ke depan"}
                                </li>
                              </ul>
                            </li>
                          </ul>
                          <ul
                            className={classNames(
                              projectcss.all,
                              projectcss.ul,
                              sty.ul___41RDd
                            )}
                          >
                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.li__ncDTn
                              )}
                            >
                              {"Surat permohonan dilakukannya pencatatan;"}
                            </li>
                          </ul>
                          <ul
                            className={classNames(
                              projectcss.all,
                              projectcss.ul,
                              sty.ul___701Yy
                            )}
                          >
                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.li___9Jqog
                              )}
                            >
                              {
                                "Surat pernyataan bersedia mematuhi peraturan perundang-undangan di Indonesia"
                              }
                            </li>
                          </ul>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__oHAps
                            )}
                          >
                            {
                              "Selengkapnya dapat dilihat pada formulir pendaftaran atau panduan pengisian pendaftaran pada bagian dokumen."
                            }
                          </div>
                        </Collapsible>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__hqmu6
                        )}
                      >
                        <Collapsible
                          className={classNames(
                            "__wab_instance",
                            sty.collapsible__ooYc8
                          )}
                          slot={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__p1LLl
                              )}
                            >
                              {
                                "Apakah implikasi dari status tercatat, dibina, dan diawasi pada regulatory sandbox?"
                              }
                            </div>
                          }
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___0Y0A8
                            )}
                          >
                            <React.Fragment>
                              <React.Fragment>
                                {
                                  "Penyelenggara IDK yang mendapatkan status tercatat belum dianggap sebagai peserta "
                                }
                              </React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ fontStyle: "italic" }}
                              >
                                {"regulatory sandbox"}
                              </span>
                              <React.Fragment>
                                {
                                  ". Penyelenggara IDK yang resmi tergabung dalam "
                                }
                              </React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ fontStyle: "italic" }}
                              >
                                {"regulatory sandbox "}
                              </span>
                              <React.Fragment>
                                {
                                  "adalah yang telah memiliki status 'diawasi' dan 'dibina' sejak proses pengkategorian dan seleksi. Peserta yang memiliki status 'diawasi' dan 'dibina' dapat memasang identitas visual yang menandakan status kepesertaannya dalam "
                                }
                              </React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ fontStyle: "italic" }}
                              >
                                {"regulatory sandbox "}
                              </span>
                              <React.Fragment>
                                {
                                  "sesuai ketentuan yang berlaku, serta akan dipantau dan diawasi secara partisipatif dalam prosesnya."
                                }
                              </React.Fragment>
                            </React.Fragment>
                          </div>
                        </Collapsible>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__uzDyh
                        )}
                      >
                        <Collapsible
                          className={classNames(
                            "__wab_instance",
                            sty.collapsible__fgdrr
                          )}
                          slot={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__eApU
                              )}
                            >
                              {
                                "Berapa lama masa berlaku rekomendasi yang diberikan ?"
                              }
                            </div>
                          }
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__xmztM
                            )}
                          >
                            <React.Fragment>
                              <React.Fragment>
                                {
                                  "Lama waktu rekomendasi dan pembinaan yang diberikan kepada Penyelenggara IDK akan ditentukan oleh Kementerian Kesehatan dengan pertimbangan tim panel "
                                }
                              </React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ fontStyle: "italic" }}
                              >
                                {"Regulatory Sandbox"}
                              </span>
                              <React.Fragment>
                                {
                                  ". Rekomendasi dapat diperbaharui setelah satu (1) tahun apabila diperlukan."
                                }
                              </React.Fragment>
                            </React.Fragment>
                          </div>
                        </Collapsible>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___5E5W
                        )}
                      >
                        <Collapsible
                          className={classNames(
                            "__wab_instance",
                            sty.collapsible__e0T21
                          )}
                          slot={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__yAhZm
                              )}
                            >
                              {
                                "Apakah akan dilakukan monitoring dan evaluasi berjalan pada inovasi yang direkomendasikan ?"
                              }
                            </div>
                          }
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__qOTl
                            )}
                          >
                            <React.Fragment>
                              <React.Fragment>
                                {
                                  "Monitoring dan evaluasi berjalan akan dilakukan kepada Penyelenggara IDK dengan status 'dibina' dan 'diawasi'. Kementerian Kesehatan mensyaratkan peserta "
                                }
                              </React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ fontStyle: "italic" }}
                              >
                                {"regulatory sandbox "}
                              </span>
                              <React.Fragment>
                                {
                                  "dengan status “dibina” untuk melakukan laporan berkala kepada Kementerian Kesehatan sebagai bahan monitoring dan evaluasi. Beriringan dengan hal tersebut, Kementerian Kesehatan RI membuka ruang pengawasan partisipatif yang dapat digunakan juga sebagai sarana monitoring dan evaluasi. Pengawasan partisipatif dilaksanakan dengan mengajak Kementerian/Lembaga terkait, asosiasi bisnis dan profesi, serta organisasi lainnya yang berkepentingan."
                                }
                              </React.Fragment>
                            </React.Fragment>
                          </div>
                        </Collapsible>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__dRbti
                        )}
                      >
                        <Collapsible
                          className={classNames(
                            "__wab_instance",
                            sty.collapsible__wzNuR
                          )}
                          slot={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__kxaPm
                              )}
                            >
                              {
                                "Bagaimana alur dari pelaksanaan regulatory sandbox?"
                              }
                            </div>
                          }
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__tllEx
                            )}
                          >
                            {
                              "Alur dari pelaksanaan regulatory sandbox dapat diunduh di bagian dokumen"
                            }
                          </div>
                        </Collapsible>
                      </div>
                      <div
                        className={classNames(projectcss.all, sty.freeBox__iOY)}
                      >
                        <Collapsible
                          className={classNames(
                            "__wab_instance",
                            sty.collapsible__yTr4G
                          )}
                          slot={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__rTgz5
                              )}
                            >
                              {
                                "Syarat dan ketentuan mendaftar regulatory sandbox"
                              }
                            </div>
                          }
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__tadQb
                            )}
                          >
                            {
                              "1. Pelaku usaha non perseorangan\n2. Terdaftar sebagai PSE di Kementerian Komunikasi dan Informatika\n3. Isi dan lengkapi formulir pendaftaran (link)\n4. Unggah dokumen berikut (format PDF) pada formulir pendaftaran untuk kelengkapan administrasi:\na. Company deck\nb. Surat Pernyataan (unduh template)"
                            }
                          </div>
                        </Collapsible>
                      </div>
                    </div>
                  </div>
                </div>
              </p.Stack>
            ) : null}
          </div>
          <div
            data-plasmic-name={"who2"}
            data-plasmic-override={overrides.who2}
            className={classNames(projectcss.all, sty.who2)}
          >
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__bkjrg)}
              >
                {true ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.columns__wIm5D)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.column__twxXl)}
                    >
                      <h2
                        className={classNames(
                          projectcss.all,
                          projectcss.h2,
                          projectcss.__wab_text,
                          sty.h2___3ZQlU
                        )}
                      >
                        {"Hubungi Kami"}
                      </h2>
                      {true ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___6UuK8
                          )}
                        >
                          <React.Fragment>
                            <React.Fragment>
                              {
                                "Untuk pertanyaan umum Anda dapat mengirimkan email ke "
                              }
                            </React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ color: "#FFFEFE", fontWeight: 700 }}
                            >
                              {"regulatory-sandbox@kemkes.go.id"}
                            </span>
                            <React.Fragment>
                              {
                                ",  jangan ragu untuk menghubungi kami jika anda memiliki pertanyaan seputar regulatory sandbox."
                              }
                            </React.Fragment>
                          </React.Fragment>
                        </div>
                      ) : null}
                    </p.Stack>
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.column__bvv7P)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__zaAf)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"none" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"60%" as const}
                        loading={"lazy" as const}
                        src={{
                          src: "/plasmic/sandbox_satuhsehat/images/mailSandpng.png",
                          fullWidth: 710,
                          fullHeight: 710,
                          aspectRatio: undefined
                        }}
                      />
                    </p.Stack>
                  </p.Stack>
                ) : null}
              </p.Stack>
            ) : null}
          </div>
          <p.Stack
            as={"div"}
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            hasGap={true}
            className={classNames(projectcss.all, sty.footer)}
          >
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__cuwSy)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__vOyNd
                )}
              >
                {"© Kementerian Kesehatan RI "}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__yYcig
                )}
              >
                {
                  "Jl. HR. Rasuna Said Blok X5 Kav. 4-9\nJakarta Selatan, Jakarta, Indonesia 12950\n"
                }
              </div>
            </p.Stack>
          </p.Stack>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "pageMetadataOverride",
    "header",
    "navigationBar",
    "hero",
    "about",
    "why",
    "who",
    "card5",
    "card6",
    "card7",
    "card8",
    "faq",
    "who2",
    "footer"
  ],
  pageMetadataOverride: ["pageMetadataOverride"],
  header: ["header", "navigationBar"],
  navigationBar: ["navigationBar"],
  hero: ["hero"],
  about: ["about"],
  why: ["why"],
  who: ["who", "card5", "card6", "card7", "card8"],
  card5: ["card5"],
  card6: ["card6"],
  card7: ["card7"],
  card8: ["card8"],
  faq: ["faq"],
  who2: ["who2"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  pageMetadataOverride: typeof PlasmicHead;
  header: "div";
  navigationBar: typeof NavigationBar;
  hero: "section";
  about: "div";
  why: "div";
  who: "div";
  card5: "div";
  card6: "div";
  card7: "div";
  card8: "div";
  faq: "div";
  who2: "div";
  footer: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicOldHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicOldHomepage__VariantsArgs;
    args?: PlasmicOldHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicOldHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicOldHomepage__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicOldHomepage__ArgProps,
          internalVariantPropNames: PlasmicOldHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicOldHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicOldHomepage";
  } else {
    func.displayName = `PlasmicOldHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicOldHomepage = Object.assign(
  // Top-level PlasmicOldHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    pageMetadataOverride: makeNodeComponent("pageMetadataOverride"),
    header: makeNodeComponent("header"),
    navigationBar: makeNodeComponent("navigationBar"),
    hero: makeNodeComponent("hero"),
    about: makeNodeComponent("about"),
    why: makeNodeComponent("why"),
    who: makeNodeComponent("who"),
    card5: makeNodeComponent("card5"),
    card6: makeNodeComponent("card6"),
    card7: makeNodeComponent("card7"),
    card8: makeNodeComponent("card8"),
    faq: makeNodeComponent("faq"),
    who2: makeNodeComponent("who2"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicOldHomepage
    internalVariantProps: PlasmicOldHomepage__VariantProps,
    internalArgProps: PlasmicOldHomepage__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Regulatory Sandbox | Kemenkes RI",
      description:
        "Regulatory sandbox adalah mekanisme pengujian bagi penyelenggara inovasi digital kesehatan (IDK) yang dilakukan oleh Kementerian Kesehatan RI (Kemenkes)",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicOldHomepage;
/* prettier-ignore-end */
